name: 'Unassign contributor after days of inactivity'
description: 'This action will unassign any issue after days of inactivity. Best used together with actions/stale.'
author: 'Boundfox Studios'
branding:
  icon: user-minus
  color: gray-dark
inputs:
  token:
    description: 'GitHub token'
    required: false
    default: ${{ github.token }}
  last-activity:
    required: true
    description: 'Days of last activity in an issue (checked against updatedAt). Defaults to 7 days'
    default: '7'
  labels:
    required: false
    description: 'Comma-separated list of labels for issues to search for. Defaults to "Stale"'
    default: 'Stale'
  exempt-assignees:
    required: false
    description: 'Comma-separated list of assignees names that never will be unassigned'
  labels-to-remove:
    required: false
    description: 'Comma-separated list of labels to remove after unassignment'
    default: 'Stale'
  message:
    required: false
    description: 'Message to comment on the unassigned issue'
    default: 'Due to longer inactivity, this issue has been unassigned automatically.'
runs:
  using: 'node16'
  main: 'dist/index.js'
